### ISSUE TITLE
Upgrade to credit card processor

### ISSUE THREAD

**Issue by RavenAtCHTN** [CHTNEastern/ScienceServerv4.0#29]
"Elain Rymsza" rymsza@isc.upenn.edu
Zack, 
Below are the URLs and information that we discussed during our call. just let me know you have additional questions or need other examples/information

ELAINE
two examples of penn web applications currently using Cybersource for their payment page

1) transcript request
http://www.upenn.edu/registar/student-services/transcrpits.html 
you will need to log into Penn-In-Touch and follow screens for a 'paper' transcript. This will take you to the Cybersource payment page 

2) online giving 
click on the "Give to Penn" tab from the Penn Homepage (http://www.upenn.edu/)
Fill out the screens to make a gift: eventually you get to the "payment" screen which is in Cybersource

3) Cybersource Manuals
Support home page
http://www.cybersource.com/developers/
Secure Acceptance Manuals are located at 
http://www.cybersource.com/developers/integration_methods/secure_acceptance/
User Data 
in the Secure Acceptance Manual search for merchant_defined_data# (in the API Fields section):
(http://apps.cybersource.com/library/documentation/dev_guids/Secure_Acceptance_SOP/html/wwhelp/wwhimp/js/html/wwhelp.htn#href=app_fields_SOP.html)

the merchant_defined_data# is a 100 byte area that can be used to store application data within Cybersource

**Comment by ZackvM** [comment]
This is finished ...
